-- SQL Server 2016+; run once in an empty database (dbo schema).
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET ARITHABORT ON;
SET NUMERIC_ROUNDABORT OFF;
GO

-- 1. BANG DOC LAP (Khong chua khoa ngoai)
CREATE TABLE TENANT (
    TenantID VARCHAR(36) PRIMARY KEY CLUSTERED,
    TenantName NVARCHAR(255) NOT NULL,
    SystemConfig NVARCHAR(MAX) NULL,
    CONSTRAINT CK_Tenant_SystemConfig CHECK
        (SystemConfig IS NULL OR ISJSON(SystemConfig) = 1)
);
GO

CREATE TABLE ROLE (
    RoleID INT PRIMARY KEY CLUSTERED,
    RoleName NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE CUSTOMER (
    CustomerID VARCHAR(36) PRIMARY KEY CLUSTERED,
    WalletAddress VARCHAR(100) NULL,
    Email VARCHAR(255) NULL
);
GO

-- 2. BANG PHU THUOC CAP 1
CREATE TABLE MERCHANT (
    MerchantID VARCHAR(36) PRIMARY KEY CLUSTERED,
    TenantID VARCHAR(36) NOT NULL,
    BusinessName NVARCHAR(255) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    CONSTRAINT CK_Merchant_Status CHECK (Status IN ('Active', 'Suspended')),
    CONSTRAINT FK_Merchant_Tenant FOREIGN KEY (TenantID) REFERENCES TENANT(TenantID) ON DELETE NO ACTION
);
GO

-- 3. BANG PHU THUOC CAP 2
CREATE TABLE [USER] (
    UserID VARCHAR(36) PRIMARY KEY CLUSTERED,
    MerchantID VARCHAR(36) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    RoleID INT NOT NULL,
    ManagerID VARCHAR(36) NULL,
    CONSTRAINT FK_User_Manager FOREIGN KEY (ManagerID)
        REFERENCES [USER](UserID) ON DELETE NO ACTION,
    CONSTRAINT CK_User_NotSelfManager CHECK
        (ManagerID IS NULL OR ManagerID <> UserID),
    CONSTRAINT FK_User_Merchant FOREIGN KEY (MerchantID) REFERENCES MERCHANT(MerchantID) ON DELETE NO ACTION,
    CONSTRAINT FK_User_Role FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID) ON DELETE NO ACTION
);
GO

CREATE TABLE API_CREDENTIAL (
    KeyID VARCHAR(36) PRIMARY KEY CLUSTERED,
    MerchantID VARCHAR(36) NOT NULL,
    ApiKey VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_API_ApiKey UNIQUE (ApiKey),
    SecretHash VARCHAR(255) NOT NULL,
    CONSTRAINT FK_API_Merchant FOREIGN KEY (MerchantID) REFERENCES MERCHANT(MerchantID) ON DELETE NO ACTION
);
GO

CREATE TABLE CAMPAIGN (
    CampaignID VARCHAR(36) PRIMARY KEY CLUSTERED,
    MerchantID VARCHAR(36) NOT NULL,
    CampaignName NVARCHAR(255) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    CONSTRAINT CK_Campaign_Dates CHECK
        (EndDate IS NULL OR EndDate >= StartDate),
    Status VARCHAR(20) NOT NULL,
    CONSTRAINT CK_Campaign_Status CHECK (Status IN ('Draft', 'Active', 'Expired')),
    CONSTRAINT FK_Campaign_Merchant FOREIGN KEY (MerchantID) REFERENCES MERCHANT(MerchantID) ON DELETE NO ACTION
);
GO

CREATE TABLE CREDIT (
    CreditID VARCHAR(36) PRIMARY KEY CLUSTERED,
    CustomerID VARCHAR(36) NOT NULL,
    MerchantID VARCHAR(36) NOT NULL,
    AvailableBalance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT UQ_Credit_Customer_Merchant UNIQUE (CustomerID, MerchantID),
    CONSTRAINT CK_Credit_Balance CHECK (AvailableBalance >= 0),
    CONSTRAINT FK_Credit_Customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE NO ACTION,
    CONSTRAINT FK_Credit_Merchant FOREIGN KEY (MerchantID) REFERENCES MERCHANT(MerchantID) ON DELETE NO ACTION
);
GO

-- 4. BANG PHU THUOC CAP 3
CREATE TABLE REWARD_RULE (
    RuleID VARCHAR(36) PRIMARY KEY CLUSTERED,
    CampaignID VARCHAR(36) NOT NULL,
    ActionType VARCHAR(50) NOT NULL,
    PointsMultiplier DECIMAL(5,2) NOT NULL,
    CONSTRAINT CK_Rule_Multiplier CHECK (PointsMultiplier > 0),
    CONSTRAINT FK_Rule_Campaign FOREIGN KEY (CampaignID) REFERENCES CAMPAIGN(CampaignID) ON DELETE NO ACTION
);
GO

CREATE TABLE CREDIT_TRANSACTION (
    TransactionID VARCHAR(36) PRIMARY KEY CLUSTERED,
    CreditID VARCHAR(36) NOT NULL,
    CampaignID VARCHAR(36) NULL,
    Amount DECIMAL(18,2) NOT NULL,
    TransactionType VARCHAR(50) NOT NULL,
    SuiTxDigest VARCHAR(100) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT CK_Trans_Type CHECK
        (TransactionType IN ('Earn', 'Redeem', 'Refund')),
    CONSTRAINT CK_Trans_Amount CHECK (
        (TransactionType = 'Earn' AND Amount > 0) OR
        (TransactionType = 'Redeem' AND Amount < 0) OR
        (TransactionType = 'Refund' AND Amount <> 0)
    ),
    CONSTRAINT FK_Trans_Credit FOREIGN KEY (CreditID) REFERENCES CREDIT(CreditID) ON DELETE NO ACTION,
    CONSTRAINT FK_Trans_Campaign FOREIGN KEY (CampaignID) REFERENCES CAMPAIGN(CampaignID) ON DELETE NO ACTION
);
GO

-- Nullable identifiers: multiple NULLs, unique non-NULL values.
CREATE UNIQUE NONCLUSTERED INDEX UX_Customer_WalletAddress
ON CUSTOMER(WalletAddress) WHERE WalletAddress IS NOT NULL;
GO
CREATE UNIQUE NONCLUSTERED INDEX UX_Trans_SuiTxDigest
ON CREDIT_TRANSACTION(SuiTxDigest) WHERE SuiTxDigest IS NOT NULL;
GO

-- FK indexes. CustomerID is already the leading key of the CREDIT unique index.
CREATE NONCLUSTERED INDEX IX_Merchant_TenantID ON MERCHANT(TenantID);
CREATE NONCLUSTERED INDEX IX_User_MerchantID ON [USER](MerchantID);
CREATE NONCLUSTERED INDEX IX_User_RoleID ON [USER](RoleID);
CREATE NONCLUSTERED INDEX IX_User_ManagerID ON [USER](ManagerID);
CREATE NONCLUSTERED INDEX IX_API_MerchantID ON API_CREDENTIAL(MerchantID);
CREATE NONCLUSTERED INDEX IX_Campaign_MerchantID ON CAMPAIGN(MerchantID);
CREATE NONCLUSTERED INDEX IX_Credit_MerchantID ON CREDIT(MerchantID);
CREATE NONCLUSTERED INDEX IX_Rule_CampaignID ON REWARD_RULE(CampaignID);
CREATE NONCLUSTERED INDEX IX_Trans_Credit_CreatedAt
ON CREDIT_TRANSACTION(CreditID, CreatedAt DESC);
CREATE NONCLUSTERED INDEX IX_Trans_CampaignID ON CREDIT_TRANSACTION(CampaignID);
GO
